<a href="https://colab.research.google.com/github/Ray-Mun-Ben/-AI-Coursework-2025/blob/main/Netflix_Titles_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from google.colab import drive
#from google.colab import files
#uploaded = files.upload()
drive.mount('/content/drive')

Mounted at /content/drive

1. How many rows and columns are contained in the dataset?

In [24]:
import pandas as pd
#df = pd.read_csv('netflix_titles.csv')
df = pd.read_csv('/content/drive/MyDrive/netflix_titles.csv')

In [25]:
df.shape

(8807, 12)

2. What datatypes are contained in the dataset?

In [11]:
df.info()
#or df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

3. Is the dataset complete? i.e no missing values?

Director, cast, country, date_added, rating and duration have missing values.

In [13]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

4. List the number of Movies and TV Shows among the last 20 rows
of the dataset.

In [14]:
df.tail(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8787,s8788,Movie,You Can’t Fight Christmas,Kenny Young,"Brely Evans, Andra Fuller, Persia White, Porsc...",United States,"December 19, 2017",2017,TV-PG,85 min,"Comedies, Romantic Movies",After stepping in to revitalize his family's h...
8788,s8789,Movie,You Carry Me,Ivona Juka,"Lana Baric, Vojislav Brajovic, Natasa Janjic, ...","Croatia, Slovenia, Serbia, Montenegro","July 1, 2016",2015,TV-MA,157 min,"Dramas, International Movies","A soap opera producer, director and makeup art..."
8789,s8790,Movie,You Changed My Life,Cathy Garcia-Molina,"John Lloyd Cruz, Sarah Geronimo, Rayver Cruz, ...",Philippines,"February 27, 2019",2009,TV-PG,116 min,"Comedies, Dramas, International Movies",Laida and Miggy think they've found perfect ha...
8790,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,UR,113 min,"Action & Adventure, Comedies",An Israeli counterterrorism soldier with a sec...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...
8792,s8793,Movie,Young Tiger,Mu Chu,"Qiu Yuen, Charlie Chin, Jackie Chan, Hu Chin, ...",Hong Kong,"November 1, 2016",1973,NR,81 min,"Action & Adventure, International Movies","Aided only by a tough female police officer, a..."
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,88 min,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...
8794,s8795,Movie,اشتباك,Mohamed Diab,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

1. Give the number of all Movies originating from South Africa

In [10]:
SouthAfricanMovies = df.query("type == 'Movie' and country == 'South Africa'")
len(SouthAfricanMovies)

24

In [9]:
SouthAfricanMovies[['title', 'release_year', 'director']].head()

                             title  release_year        director
293                           Slay          2021       Adze Ugah
764   Trippin' with the Kandasamys          2021   Jayan Moodley
881                 I Am All Girls          2021   Donovan Marsh
1172       Loyiso Gola: Unlearning          2021   Kagiso Lediga
1905                  Cold Harbour          2013  Carey McKenzie

2. What is the description of the movie in the 12th row?

In [11]:
df.iloc[11]['description']

'Struggling to earn a living in Bangkok, a man joins an emergency rescue service and realizes he must unravel a citywide conspiracy.'

3. From these South African movies, list only those released in 2021

In [13]:
SA_Movies_2021 = df.query("type == 'Movie' and country == 'South Africa' and release_year == 2021")
SA_Movies_2021[['title', 'release_year', 'description']]

,title,release_year,description
293,Slay,2021,"In pursuit of both success and validation, a g..."
764,Trippin' with the Kandasamys,2021,"To rekindle their marriages, best friends-turn..."
881,I Am All Girls,2021,A relentless detective finds common ground wit...
1172,Loyiso Gola: Unlearning,2021,South African comedian Loyiso Gola serves up f...

4. List the entire cast of all movies released in 2021.

In [18]:
Movies2021 = df.query("type == 'Movie' and release_year == 2021")
Movies2021['cast']

6       Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
9       Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
12      Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
13      Klara Castanho, Lucca Picon, Júlia Gomes, Marc...
18      Freida Pinto, Logan Marshall-Green, Robert Joh...
                              ...
1425                                                  NaN
1431    Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...
1436    Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...
1466                                                  NaN
1468             Cha In-pyo, Cho Dal-hwan, Song Jae-ryong
Name: cast, Length: 277, dtype: object